author:
  name   : "Cassidy Amundsen"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Linguist | NLP Enthusiast | Data Analyst"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/cassidyamundsen"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/cassidy-amundsen123/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:amundsen.cassidy@gmail.com"
title: Cassidy Amundsen
description: >-
  Linguist & NLP enthusiast exploring the intersection of language and technology.
url: "https://cassidyamundsen.github.io"
baseurl: ""
minimal_mistakes_skin: air
remote_theme: "mmistakes/minimal-mistakes@4.27.0"

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
