title: Cassidy Amundsen
email: amundsen.cassidy@gmail.com
description: >-
  Linguist & NLP enthusiast exploring the intersection of language, data, and technology.

url: "https://cassidyamundsen.github.io"
baseurl: ""
github_username: cassidyamundsen

remote_theme: "mmistakes/minimal-mistakes@4.27.0"
minimal_mistakes_skin: air

permalink: /:title/
timezone: America/New_York

include:
  - _pages
  - _includes
  - assets/css

collections: {}

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author (optional)
author:
  name: Cassidy Amundsen
