title: Cassidy Amundsen
email: amundsen.cassidy@gmail.com
description: >-
  Linguist & NLP enthusiast exploring the intersection of language and technology.
url: "https://cassidyamundsen.github.io"
baseurl: ""
github_username: cassidyamundsen
minimal_mistakes_skin: air
search: true

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.27.0"

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: America/New_York
title_separator: "|"

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Cassidy Amundsen"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Linguist + data analyst exploring how people communicate through language and tech."
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/cassidyamundsen"
    - label:
