title: Cassidy Amundsen
email: amundsen.cassidy@gmail.com
description: >-
  Linguist & data analyst exploring the intersection of language and technology.

url: "https://cassidyamundsen.github.io"
baseurl: ""
github_username: cassidyamundsen

remote_theme: "mmistakes/minimal-mistakes@4.27.0"
minimal_mistakes_skin: "air"

permalink: /:categories/:title/
timezone: America/New_York

# Remove posts entirely
collections: {}

# Turn on page support
include:
  - _pages

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
