title: Cassidy Amundsen
description: Bridging Language and Technology through NLP
url: "https://cassidyamundsen.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: air
locale: en-US

author:
  name: Cassidy Amundsen
  avatar: "/assets/images/bio-photo.jpg"
  bio: Linguist | NLP Enthusiast | Data Analyst
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/cassidyamundsen"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/cassidy-amundsen123/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:amundsen.cassidy@gmail.com"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cassidyamundsen"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/cassidy-amundsen123/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:amundsen.cassidy@gmail.com"
      atom_feed:
  hide: true


include:
  - _pages
